name: Windows RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Enable RDP
        run: |
          reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          netsh advfirewall firewall set rule group="remote desktop" new enable=Yes
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0

      - name: Get IP Address
        run: |
          $ip = (Invoke-WebRequest -Uri "http://ifconfig.me/ip").Content
          echo "Your Windows RDP IP: $ip"
